Repository gitbutlerapp/gitbutler, pull requests merged in 2024-03, with the labels that each got.

#3013 fix list item overflow on windows
  gitbutler-ui/src/lib/components/ListItem.svelte
Labels: os:windows

#3161 style: Update button size design token
  gitbutler-ui/src/styles/tokens.css
Labels: UI

#3341 style fix: tag component
  gitbutler-ui/src/lib/components/Tag.svelte
Labels: 🎨 UI

#3337 accessibility fix: commit card folding behaviour on keyup
  gitbutler-ui/src/lib/components/CommitCard.svelte
Labels: 🚹 accessibility
